### ISSUE TITLE
Quality/Audio

### ISSUE THREAD

**Issue by bakes82** [s0len/meta-manager-config#1]
How would you add the quality IE 1080P/4k HDR/DV maybe to the bottom left corner and audio for like Atmos?

**Comment by s0len** [comment]
That would require changing the actual image right now. I will be trying out a different approach to those images, maybe, if what i'm thinking is right, we can then make this much more granular and set the position according to your preferences.

**Comment by bakes82** [comment]
Yes it would require creating new images for the quality as either another "bar/sash" thing for top left, or corner images if they went in bottom left.  I thought he posted the PSD, honestly I think I just need the images created, you should be able to do something like this also to add the quality if the images existed for the current corner style

![image](https://github.com/s0len/meta-manager-config/assets/3197191/cbad9ea3-6970-4fac-881f-7342636805cb)

**Comment by s0len** [comment]
I will close this as it's not really an issue and I wont be creating the images for the upper left corner as I don't like it
