### ISSUE TITLE
Errors applying network overlays

### ISSUE THREAD

**Issue by SpartacusIam** [s0len/meta-manager-config#17]
I'm getting the following errors when running the network overlays.  I'm not sure if these are intentional or if I'm going to run into an issue with these networks.

https://dpaste.org/uHUiE

https://dpaste.org/hao3Y

**Comment by s0len** [comment]
Alright the missing networks have been added. The one #0 I dunno how to resolve as the problem lies with the # in the filename. It's known and ignored on my part until something changes
