### ISSUE TITLE
missing award ribbons

### ISSUE THREAD

**Issue by ymendel** [s0len/meta-manager-config#18]
I'd like to have ribbons for a few more awards, at least BAFTA and Sundance. I could try making them myself, but there doesn't seem to be a blank lower-right ribbon image. I tried rotating the streaming background, but that's flat black and missing the gradient.

Similarly, I'm not sure if you can make something for "certified fresh" on Rotten Tomatoes. I'm not sure what would be a good differentiator there. Right now I'm just using gold to mean 100% and silver to be certified fresh.

Also, just thanks for the repo in general. I got here because the TV show status top-left ribbons are wonderful, so much better than the default text that often covers up interesting parts of the poster.

**Comment by s0len** [comment]
Sorry it's not an issue but a request. I am currently unable to fulfill this request as my time needs to be spent elsewhere
