### ISSUE TITLE
F1 yml

### ISSUE THREAD

**Issue by effoc** [s0len/meta-manager-config#26]
not updated to the new pictures you made :-)
Awesome work by the way love it

**Comment by s0len** [comment]
Sorry I didn't realised you had a question and completely missed it :)

anyways, if you experience chaching issues like what you suggested it is resolved by deleting Kometa cache and rerunning it.

Thanks for your kind words

**Comment by effoc** [comment]
No issue whit chaching the file was not there for canadas race

**Comment by s0len** [comment]
But it's working now?
I'm asking as when I look now I can see the canada race image was added 3 weeks ago and the code which displays it is also present so it should work
