### ISSUE TITLE
Old Shows Just Added poster missing white border

### ISSUE THREAD

**Issue by scottgigawatt** [s0len/meta-manager-config#32]
Minor detail, but the old shows just added poster is missing the white border like the other posters.

- https://github.com/s0len/meta-manager-config/blob/s0len-patch-1/posters/new-releases/Old_Shows_Just_Added.jpg

<img src="https://github.com/s0len/meta-manager-config/blob/main/posters/new-releases/Old_Shows_Just_Added.jpg?raw=true" alt="Old_Shows_Just_Added" width="200"/>

The new tv shows just added poster has the white border:

- https://github.com/s0len/meta-manager-config/blob/main/posters/new-releases/New_TV_Show_Releases.jpg

<img src="https://github.com/s0len/meta-manager-config/blob/main/posters/new-releases/New_TV_Show_Releases.jpg?raw=true" alt="New_TV_Show_Releases" width="200"/>

**Comment by s0len** [comment]
Nice find! I'll fix it 👍🏻

**Comment by s0len** [comment]
It's been corrected
