### ISSUE TITLE
Missing Networks

### ISSUE THREAD

**Issue by TRaSH-** [s0len/meta-manager-config#4]
I've a bunch of series from the following networks, that have missing logo's

- [ ] TV-MA
- [ ] TV-14
- [ ] TV-PG

**Comment by s0len** [comment]
are those really networks? I can't seem to find them in https://github.com/meisnate12/Plex-Meta-Manager-Images/tree/master/network/logos and when searching i'm unsure which logo is the right one. I also need the correct filename if i'm going to do these blind
